### ISSUE TITLE
questions about yasm.targets and yasm.props.

### ISSUE THREAD

**Issue by fuchanghao** [pinterf/mvtools#2]
I couldn't find these files in yasm official page.

I change the files of mvtools.vcxproj use vsyasm instead of yasm

<Import Project="$(VCTargetsPath)\BuildCustomizations\vsyasm.props" />
<Import Project="$(VCTargetsPath)\BuildCustomizations\vsyasm.targets" />

it's successful with yasm 1.3.0.28.g51af.

but I don't know what really those files are and I'm not sure it worked as expected.

**Comment by pinterf** [comment]
Yes, I simply renamed the files to work, I think this is the way it works. Some have problems with 1.3 (VapourSynth maybe?) so 1.2 yasm can also be good.
Btw, quick test, my Visual Studio compilation fails, complaining to yasm, I don't know what I have done (update 3?), it worked some month ago (Now I used intel beta compiler in VS2015 environment last time because of inline assembly that would not compile in x64 with VS2015)

**Comment by fuchanghao** [comment]
official 1.3.0 release have problems with -f Win32.
It could only read -f win32.
the leatest git built(with VS2015 UP3 and Cmake 3.6.1) don't have such a problem.
