### ISSUE TITLE
Can't find libfftw3f-3.dll

### ISSUE THREAD

**Issue by ccicnce113424** [pinterf/mvtools#36]
I put libfftw3f-3.dll in the directory of mvtools, but mvtools couldn't find it. I have to put libfftw3f-3.dll in the system32 directory for mvtools to work properly. So I can't package this filter with my AVS script.

**Comment by pinterf** [comment]
Masktools doesn't need this file. Perhaps your other filter needs it (neo)Fft3dfilter or (neo)dfttest or mvtools2

**Comment by ccicnce113424** [comment]
> Masktools doesn't need this file. Perhaps your other filter needs it (neo)Fft3dfilter or (neo)dfttest or mvtools2

I'm sorry. I mistyped. It's mvtools.

**Comment by pinterf** [comment]
I think because of Windows DLL search order rules you have to put it either in the System32 directory (which you don't like) or next to the actual consumer exe program (e.g. it worked for me when I have put the dll next to VirtualDub64.exe when I invoked Avisynth script from there). You can probably ask this on doom9 forum, authors of other tools can probably help you with this (e.g. how it is done in MeGUI, Staxrip, etc.) this is not strictly mvtools2 releated I think.

**Comment by ccicnce113424** [comment]
I see. Thanks.
